# Generated by Django 4.2.2 on 2024-01-05 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('U', 'не выбран'), ('M', 'мужской'), ('F', 'женский')], default='U', max_length=1, verbose_name='Пол')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('site_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт')),
                ('telegram_link', models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка на Telegram')),
                ('user_avatar', models.ImageField(blank=True, null=True, upload_to='user/avatars/', verbose_name='Аватар пользователя')),
                ('show_email', models.BooleanField(default=False, verbose_name='Отображать Email?')),
                ('show_telegram', models.BooleanField(default=False, verbose_name='Отображать Telegram?')),
                ('show_last_name', models.BooleanField(default=False, verbose_name='Отображать фамилию?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
